eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8777

spring:
  application:
    name: checkout-stripe

application:
  config:
    stripe-url: http://localhost:8222/stripe


management:
  tracing:
    sampling:
      probability: 1.0
